---
collections:
  - name: cloud.terraform
  - name: amazon.aws
  - name: ansible.posix
  - name: community.general
  - name: https://github.com/k3s-io/k3s-ansible.git
    type: git
    version: 1.1.1
  - name: kubernetes.core
