name: Ansible Manual

on:
  workflow_dispatch:
    inputs:
      playbook:
        description: Playbook filename under src/ansible/playbooks/
        required: true
        type: choice
        options:
          - base-os-updates.yml
          - bootstrap.yml
          - apply.yml
      initialize-terraform:
        description: Initialize Terraform first
        type: boolean
        default: true

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  run:
    uses: glitchedmob/infra-gha/.github/workflows/ansible-run.yml@v0.7.1
    with:
      working-directory: src/ansible
      initialize-terraform: ${{ inputs.initialize-terraform }}
      terraform-working-directory: src/tf
      playbook: ${{ inputs.playbook }}
      headscale-login-server: https://headscale.levizitting.com
    secrets:
      envrc_content: |
        export TF_VAR_proxmox_endpoint="${{ secrets.TF_VAR_proxmox_endpoint }}"
        export TF_VAR_proxmox_api_token="${{ secrets.TF_VAR_proxmox_api_token }}"
      headscale_auth_key: ${{ secrets.HEADSCALE_AUTH_KEY }}
      aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}
      output_encryption_key: ${{ secrets.OUTPUT_ENCRYPTION_KEY }}
